[package]
name = "mnemo"
version = "0.1.0"
edition = "2024"

[dependencies]
yaml-rust = "0.4"
shellexpand = "3.1.1"
clap = { version = "4.5.54", features = ["derive", "cargo"] }
dirs = "6.0.0"
brush-parser = "0.3.0"
regex = "1.12.2"
